### ISSUE TITLE
Javadoc support

### ISSUE THREAD

**Issue by bannmann** [tomokinakamaru/silverchain#38] opened 2021-06-20 10:13 UTC
In my experience, Javadoc is not well-suited for documenting fluent APIs - users simply don't get a nice overview of the possible chains. That said, the code completion in my IDE would benefit greatly from Javadoc _on the individual methods_. For hand-written fluent APIs, this can be done.

Silverchain cannot _generate_ Javadoc comments, of course - they still must be written by a human. However, a library author certainly should not modify the Silverchain-generated sources (in my project, those are not even checked in).

How about adding new feature so that when generating any method in a `stateX` interface, Silverchain copies the Javadoc comment for that signature from somewhere? I don't care much from where - it could be one or several Java interfaces, it could be the action class (`MelodyAction` in the tutorial) or it could be something else entirely.

**Comment by tomokinakamaru** [comment] 2021-06-21 04:21
Thank you for using Silverchain :)

I like your idea to extract Javadoc comments from an action class. The action class lists the methods of generated fluent APIs, so the library author can easily check which method to add comments and find what to write while seeing the method signature and body. If we need to define dummy interfaces just for Javadoc, it would be too tedious to synchronize the comments and the implementation.

The problem of using the action class is that, we need to run Silverchain twice to generate commented fluent APIs:

1. Create an AG file and run the first generation to obtain an action interface (e.g. `silverchain --input melodychain.ag`);
2. Create an action class and add comments to the methods in the action class (by hand);
3. Run the second generation to obtain commented state classes. (e.g. `silverchain --input melodychain.ag --javadoc-source MelodyChainAction.java` )

Starting from Step 2 is possible, but it would be hard to list all the methods in advance without a generated action interface. If we write Javadoc comments in an AG file, we don't need to run the generation twice. However, I do not want to write Javadoc comments in the file without IDE supports.

Do you think such two-phase generation is acceptable?

**Comment by bannmann** [comment] 2021-06-21 15:35
I think the two-phase generation approach is perfectly fine.

My suggestion is that Silverchain just ignores `--javadoc-source` if the file does not exist yet (or prints a non-fatal warning). This way, the command line invocation for Silverchain for Step 1 and 3 can be the same. The basic process would be:

> add a basic `.ag` file, set up the Silverchain invocation once by adding it to your build scripts, run it once, then improve your `.ag` file step by step in conjunction with implementing the action classes and adding/refining the Javadoc.

Another thing: You should make sure that `--javadoc-source` accepts wildcards because one `.ag` file can result in several separate builders/action classes. Silverchain could identify the correct action class for the respective API by looking at which interface/class it implements.

**Comment by tomokinakamaru** [comment] 2021-06-22 05:24
> one .ag file can result in several separate builders/action classes

This was out of my mind, thank you for reminding me of it.

So, to summarize, the new feature would be as follows:
- Silverchain extracts Javadoc comments from action classes under the path specified by `--javadoc-source`. For example, when running `silverchain -i melodychain.ag --javadoc-source src`, Silverchain (1) reads action classes under `src` (2) finds and extracts Javadoc comments for `A()`, `B()`, `C()`, etc., and (3) finally generates commented state classes.
- When a path is specified by `--javadoc-source` and when silverchain could not find any action class, it prints a (non-fatal) warning message.
- When `--javadoc-source` is **not** specified, Silverchain simply generates non-commented state classes (as it does now)

Am I doing what you need?

**Comment by bannmann** [comment] 2021-06-22 07:25
> Am I doing what you need?

Yes, this sounds perfect!

**Comment by tomokinakamaru** [comment] 2021-06-29 12:00
I have implemented this feature in the branch [develop](https://github.com/tomokinakamaru/silverchain/tree/develop). Could you test the feature with your API definitions when you have time? (Since the option name `--javadoc-source` seemed a bit long, I changed it to just `--javadoc`. Hope you like it too.) I still want to add some tests and do some refactoring before merging it into the master branch, but I first would like to make sure that the current implementation works as you expected.

**Comment by bannmann** [comment] 2021-06-30 16:47
It seems to work only partially - of the three methods with Javadoc comments, only one gets copied to the interfaces. The most obvious difference is that of the three, it's the only one that has no arguments.

If you like, you can check out [this experimental branch](https://github.com/bannmann/puretemplate/tree/experimental/new-silverchain-syntax) and run Silverchain with `--input src/main/silverchain/puretemplate.ag --output target/generated-sources/silverchain --javadoc src/main/java/org/puretemplate` args.

Another thing: any `{@link SomeClass}` in the original Javadoc that is not fully qualified (because the class is in the same package as the action file) will become invalid when copied to the state interface as-is.

**Comment by tomokinakamaru** [comment] 2021-07-01 03:39
Thank you for the datailed feedbacks! I have fixed the first problem (caused by my stupid mistake).

I am now working on the second one, but this may take a while to fix it :( I will notify you when the second fix is done.

**Comment by tomokinakamaru** [comment] 2021-07-06 05:22
@bannmann I have implemented the name-resolving feature in the develop branch. Hope it works as you expected now, and any kinds of feedbacks are more than welcome!

**Comment by bannmann** [comment] 2021-07-09 16:02
I tested `develop` 2b997e4 and it works fine!

Thanks for implementing this feature; looking forward to having this in the `latest` docker image. 😃

**Closed** 2021-07-10 00:11 UTC
